---
- name: Install RVM package dependencies
  tags: setup
  apt: name={{item}} state=latest
  with_items:
    - curl
    - gawk
    - g++
    - gcc
    - make
    - libc6-dev
    - libreadline6-dev
    - zlib1g-dev
    - libssl-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - autoconf
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - libtool
    - bison
    - pkg-config
    - libffi-dev

# Look, I know this is a vulnerability vector but seriously, FUCK!
- name: Import RVM GPG keys
  tags: setup
  sudo: yes
  sudo_user: '{{rvm_install_user}}'
  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
  changed_when: false

- name: Install RVM for user
  tags: setup
  sudo: yes
  sudo_user: '{{rvm_install_user}}'
  shell: \curl -sSL https://get.rvm.io | bash -s {{rvm_channel}} --autolibs=fail creates=~/.rvm

- name: Install Ruby for user
  tags: setup
  sudo: yes
  sudo_user: '{{rvm_install_user}}'
  shell: ~/.rvm/bin/rvm --default install {{rvm_ruby_version}} creates=~/.rvm/rubies/ruby-{{rvm_ruby_version}}

- name: Install Bundler gem
  tags: setup
  sudo: yes
  sudo_user: '{{rvm_install_user}}'
  shell: ~/.rvm/bin/rvm default do gem install bundler --no-document
